bibcat:
    build: .
    ports:
        - "5000:5000"
    links:
     - semanticServer

semanticServer:
    image: jermnelson/semantic-server-core:dev
    ports:
     - "8080:8080"
    volumes:
     - /opt/bibcat_repository/fedora-data:/usr/share/fedora-data
     - /opt/bibcat_triplestore:/usr/share/blazegraph
